version: "3.4"
services:
  kafdrop:
    container_name: kafdrop
    image: obsidiandynamics/kafdrop
    restart: "always"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
      JVM_OPTS: "-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify"
    depends_on:
      - "kafka"

  zookeeper:
    container_name: zookeeper
    image: docker.io/bitnami/zookeeper:3.8
    restart: "always"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka-bitnami
    image: docker.io/bitnami/kafka:3.4
    restart: "always"
    ports:
      - "29092:29092"
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:29092,CONTROLLER://:9093,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_MESSAGE_MAX_BYTES=200000000
      - KAFKA_CFG_MAX_PARTITION_FETCH_BYTES=200000000
      - KAFKA_CFG_MAX_REQUEST_SIZE=200000000
    depends_on:
      - zookeeper

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/api-gateway/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    ports:
      - 3000:3000
      - 3001:3001
    depends_on:
      - kafka

  auth:
    container_name: auth
    image: auth
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/auth/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - kafka

  comm:
    container_name: comm
    image: comm
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/comm/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - kafka

  pkg_mgmt:
    container_name: pkg_mgmt
    image: pkg_mgmt
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/pkg-mgmt/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - kafka

  prod_mgmt:
    container_name: prod_mgmt
    image: prod_mgmt
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/prod-mgmt/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
      DB_PROD_MGMT_PORT: 3306
      DB_PROD_MGMT_DATABASE: aaklywkt_prod_mgmt
    depends_on:
      - kafka

  txn:
    container_name: txn
    image: txn
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/txn/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - kafka

  users:
    container_name: users
    image: users
    build:
      context: monorepo
      dockerfile: ./Dockerfile
    command: node ./dist/apps/users/main.js
    restart: "always"
    environment:
      NODE_ENV: stage
      ENV_FILE: .env.stage
      OAUTH2_GOOGLE_CLIENT_SECRET: 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
      OAUTH2_GOOGLE_CLIENT_ID: 768201973051-b9supnlu237m58th9c3du0qpp3m13cgl.apps.googleusercontent.com
      CLOUDINARY_CLOUD_NAME: nightowls19vp
      CLOUDINARY_API_KEY: 249351234153949
      CLOUDINARY_API_SECRET: njhqt4KBl2GB-97_grDYiHlNJJw
      GO_UPC_API_KEY: e2794108dccbdff9506de7bddb7f609ab719bd66baba9a7c9cd5177838538316
      KAFKA_HOST: kafka
      KAFKA_PORT: 29092
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
